services:
  mysql:
    image: mysql:8.4
    container_name: student-management-mysql
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: student_management
      MYSQL_USER: student_user
      MYSQL_PASSWORD: student_password

    ports:
      - "3306:3306"

    volumes:
      - student_mysql_data:/var/lib/mysql

volumes:
  student_mysql_data: